import { 
    Document, 
    Packer, 
    Paragraph, 
    TextRun, 
    Table, 
    TableRow, 
    TableCell, 
    WidthType, 
    BorderStyle, 
    ImageRun, 
    AlignmentType, 
    Header, 
    Footer,
    PageNumber,
    NumberFormat,
    VerticalAlign,
    HeadingLevel,
    HeightRule
} from 'docx';
import { saveAs } from 'file-saver';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Logo Base64 (Full string retrieved from system assets)
const LOGO_BASE64 = "iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAYAAAB/HSuDAAAAAXNSR0IArs4c6QAAIABJREFUeF7s3QecXWWd//Hv79yZSUIL6SGZFAREQWxgF8TG2lhx197WtaCirgULKiKIXbHv2l2x/C2suvbedpVdG64FkF4CISSZSUhCMuXO+f3v7+YEY8hkzpmZO3PvPJ/zf/H6+//n3HvP836embnne57n95g4EEAAAQQQQAABBBBAAAEEEEBgxgvYjG8hDUQAAQQQQAABBBBAAAEEEEAAAREAMAgQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQAABBBBAAAEEEEAAAQQQSECAACCBTqaJCCCAAAIIIIAAAggggAACCBAAMAYQQGBUAV/TO+fWnu6DurLBg/PM5nVnNnukbgeZj8yR1fb5+8PNNtZkeZ6NbOjJhrfdcsuszQevun4T3AhMp4BfcfgsHbh1rrpmLxi2+lzLNSe37CCZZitXc0znls822UGZfJN7Nty8Xh9x78q21Ea0w7t8c3dN27dKfQce+LxNZmfn09mmTvhsd++SNF/SIZIWSporqUfSWkl/MjN+N3RCR3KNCCCAAAIdL0AA0PFdSAMQmJiA+1E9AzdtXqru7NBM6nVpmWTLTPlSZTbXXLNdmiX5LLl1uXmPyWrynTdLox6Zdpjk7how05DcBj3TduXqiy/9Lq01aW3d62vqA7Vr5q64oX9iLeHVCOwU8IvVo6XLltRHulbVPV/tmQ7JZIeY+RKZDnbXHJNmS94jsy659cQN6m0DOlOM77g5HZRr5829ySUNy1WXaVBS3aQdLtsuqc9zvznLdGNWszWDdd2w3+yh6+3Am9en2ifuHn4rJR0r6WhJh0taKmk/SXOKm/+apJ9Jer+ZXZyqFe1GAAEEEEBgKgUIAKZSm89CYJoF3JXp4tWL6zuG7zzi2VHK/EiTr3LPFpj8QJn2d2k/2/klPf6Lp3aT+XsibqIGZNruru1ybTfzbS7bYubr89z+kskuszy/pHuxXW52w45pJuPj21ygOabXH7poIBu+k5kdJdcdzfI7uGuByQ6Q6YDbxrRpjlzdkz6mXYOWFWNaulXut5rZFjdfL9eVcrvElP2le2HPFWZXbmlz0nFfnrvHDX3c9J8o6YGS7iRpUeMGf56kg4qb/j3f/9uNSRdnmdlF4/5gXng7AXeP39sRtKyStELNYFcLJB1Q/LfrNXVJMSZvkXSzpDWSrpe00czi3zgQQAABBGaYwGR+sZ9hNDQHgc4X8HhKv3XZgvqQ3VWZHZu77mGylZLHU9C5Jh3k0v6S4ov79B6mIc+1xeLLqOkWl2/MZJdIfpFb7bc9/ddfZUc0n7xyJC6w5YblC7pn2TEmOy4zv7tMK90139Uc0mTTv6uX6Su7H9vSe3vF/m7um3H121Bfzy54piAwM4t/Zb1Zpa9xnJ7unZuT0lxvwmYVnqpNacRrzNlb+keHvx81e0w3T1CmrgB/FYjALhDpc8e38kEAIVbcaP21qLg3/zxcd72qriRvLJR6f3zkv6zKNIXS6Hiv/i3fM9t+4oK8fGzGmMgbvpjN464eT2lERz8Y7H1Y9kQL5YDXCLphUV7nphgABCWrylupMuuuY8OjC1sX25mH5/gGGi+3N0jzIkdBqKWRJn+21Zc9/llxna6k9EJvAcCbSZAANBmHcLlpCUw1Lfin8393Ny0RFEZnWM6BOLpxoDMviHzt/bMu+Hi8T45nY6Lb6fPjKf+I/MGH5mbv1PSavfSU03bqRkz4Vri5ivCrV/U865X7r/o2j+ZNW/6xjyKp/9xw3d+hRu2Md93HycQAPw1AHhmsT1bPIUf7/ez6Od4ehtPe7/f/N0m1fe82S/bYUUgFH+bYhvIqEdwWlHcrsyNZPxujWnwESLcq8J4mhEzAIqb7whAvynpgRVmUsTPb+yqcPxEK++7NwPYWMoTa//LzsCIPnuLmcWsEQ4EEJiBAuP9AzMDKWgSAlMnsL1veW/N7YNyPUJW+o/y1F1gmp+Uu9t1WaZzu3XrV5gNUH4QxFP/WzcsWtJls8410z8VX3T5+1KesFVn5mbqz93OnrVg1ifMrixVXbyYhh5PCz9YVJ9v1fXF+xIA7HxKG5Xj/13SPUs+pd2zT+KmcUPj6f4bigr0A5M5dbuYHRA3/TGN/lnFk/0VJQbGjqK4XexgUzbknjEBQBEC3L9YghDr8MseMZPnArOYRTX+w90f3qgj8e4itCnzRhcXMxa+P97QqMyHcA4CCEyvAF/QptefT09QYHBj7+PM/D3uFk95yjxFSVBpGptsNmy5n9Y9MvyFqtOnp/Gqp+2j3VUb2Nh7vJk+atIRE3hyOW1tSOCDc8nf0LNpznl2ROkQoEdSrJ3+WGM2wKEtNEo+AChmXUSl/Jh5EbUyqh5x8/+TxlPjf25Mt7+h1TduxayAqCQfVe4fWuHGvmy7ZloAEN+1Y1ZUFEKNJ/Jlj1satRqeZ2ZRv6Dy4e4R0Ly6EQy9qOTv5QgIY9eP2MGBqf+VxXkBAp0jQADQOX3FlXa4gK9bsv9gredcM4/PrLPr6vD6R/XN7+62K9sBfMAnuPudG796R9rY034Pef0l9uK8IuAZM0X6+OOf8rQIn0Yh7Kix5L2V6SjL795H5vUu6Gis78T7mDax57P3L1Z/7H8AnC878gAAAABJRU5ErkJggg==";

export const generateStrategyDataSheet = async () => {
    const doc = new Document({
        sections: [{
            properties: {
                page: {
                    size: {
                        width: 11906, // A4 Width in TWIPs
                        height: 16838 // A4 Height in TWIPs
                    }
                }
            },
            headers: {
                default: new Header({
                    children: [
                        new Paragraph({
                            children: [
                                new ImageRun({
                                    data: base64ToUint8Array(LOGO_BASE64),
                                    transformation: { width: 140, height: 40 },
                                    type: "png",
                                }),
                                new TextRun({ text: "\tSTRATEGY DATA COLLECTION SHEET", bold: true, size: 28, color: "2c185a" }),
                            ],
                            alignment: AlignmentType.LEFT,
                            spacing: { after: 200 },
                        }),
                    ],
                }),
            },
            footers: {
                default: new Footer({
                    children: [
                        new Paragraph({
                            children: [
                                new TextRun({ text: "Official Strategy Asset | www.qixads.com", color: "666666", size: 16 }),
                            ],
                            alignment: AlignmentType.CENTER,
                        }),
                    ],
                }),
            },
            children: [
                new Paragraph({
                    text: "Business Strategy Checklist",
                    heading: HeadingLevel.HEADING_1,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 400 },
                }),
                
                // Primary Data Section
                createSectionTitle("1. PRIMARY BUSINESS DATA"),
                createEmptyTable(["Field / Parameter", "Information / Values"], 6),
                
                new Paragraph({ text: "\n" }),
                
                // Digital Presence Section
                createSectionTitle("2. DIGITAL PRESENCE & ASSETS"),
                createEmptyTable(["Channel / Asset", "Current Status / Access Level"], 8),

                new Paragraph({ text: "\n" }),

                // Market Data Section
                createSectionTitle("3. MARKET INTELLIGENCE"),
                createEmptyTable(["Market Aspect", "Competitive Findings / Benchmarks"], 6),

                new Paragraph({ text: "\n" }),

                // ICA Section
                createSectionTitle("4. IDEAL CUSTOMER AVATAR (ICA)"),
                createEmptyTable(["Customer Segment", "Demographics & Psychographics"], 7),

                new Paragraph({ text: "\n" }),

                // Goals Section
                createSectionTitle("5. STRATEGIC GOALS & REVENUE TARGETS"),
                createEmptyTable(["Objective / Goal", "Target Value / Expected Result"], 5),

                new Paragraph({ text: "\n\n" }),
                new Paragraph({
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({ text: "CONTACT US FOR STRATEGY GUIDANCE", bold: true, color: "2c185a", size: 24 }),
                    ],
                }),
                new Paragraph({ 
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({ text: "Qix Ads, 2nd Floor City Center Complex, Pattambi Rd, Perinthalmanna, Kerala 679322", size: 18 }),
                    ]
                }),
                new Paragraph({ 
                    alignment: AlignmentType.CENTER,
                    children: [
                        new TextRun({ text: "Phone/WhatsApp: +91 99473 81381 / +91 8136912104 | qixads.com", size: 18, bold: true }),
                    ]
                }),
            ],
        }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, "QixAds_Strategy_Information_Sheet.docx");
};

const createSectionTitle = (text: string) => {
    return new Paragraph({
        children: [
            new TextRun({ text, bold: true, color: "2c185a", size: 22, underline: {} }),
        ],
        spacing: { before: 200, after: 120 },
    });
};

const createEmptyTable = (headers: string[], rows: number) => {
    const tableRows = [
        new TableRow({
            children: headers.map(h => new TableCell({
                shading: { fill: "f3f4f6" },
                children: [
                    new Paragraph({ 
                        alignment: AlignmentType.CENTER,
                        children: [new TextRun({ text: h, bold: true, color: "2c185a" })] 
                    })
                ],
                verticalAlign: VerticalAlign.CENTER,
            })),
        }),
    ];

    for (let i = 0; i < rows; i++) {
        tableRows.push(new TableRow({
            height: { value: 600, rule: HeightRule.ATLEAST },
            children: headers.map(() => new TableCell({
                children: [new Paragraph("")],
            })),
        }));
    }

    return new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: tableRows,
    });
};

export const generateStrategyOutcomePDF = (strategy: any, clientName: string) => {
    const doc = new jsPDF('p', 'mm', 'a4') as any;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Helper for Header
    const addHeader = () => {
        // Branding Bar
        doc.setFillColor(44, 24, 90); // Brand Purple
        doc.rect(0, 0, pageWidth, 25, 'F');
        
        // Logo Placeholder/Text
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(16);
        doc.setFont(undefined, 'bold');
        doc.text("QIX ADS", 15, 12);
        doc.setFontSize(10);
        doc.text("STRATEGY REPORT 2025", 15, 18);
        
        // Client Name
        doc.setFontSize(12);
        doc.text(clientName.toUpperCase(), pageWidth - 15, 15, { align: 'right' });
    };

    // Helper for Footer
    const addFooter = (isLastPage = false) => {
        doc.setFillColor(250, 250, 250);
        doc.rect(0, pageHeight - 15, pageWidth, 15, 'F');
        doc.setTextColor(150, 150, 150);
        doc.setFontSize(8);
        doc.text(`Qix Ads Strategy Insight | www.qixads.com | Page ${doc.internal.getNumberOfPages()}`, pageWidth / 2, pageHeight - 7, { align: 'center' });

        if (isLastPage) {
            doc.setFillColor(44, 24, 90);
            doc.rect(0, pageHeight - 60, pageWidth, 45, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(12);
            doc.setFont(undefined, 'bold');
            doc.text("CONTACT OUR STRATEGY TEAM", pageWidth / 2, pageHeight - 48, { align: 'center' });
            
            doc.setFontSize(9);
            doc.setFont(undefined, 'normal');
            doc.text("Address: 2nd floor City Center Complex, Pattambi Rd, near Supplyco Store, Perinthalmanna, Kerala 679322, India", pageWidth / 2, pageHeight - 38, { align: 'center' });
            doc.text("Email: hello@qixads.com | Website: www.qixads.com", pageWidth / 2, pageHeight - 33, { align: 'center' });
            doc.setFont(undefined, 'bold');
            doc.text("Phone/WhatsApp: +91 99473 81381 / +91 8136912104", pageWidth / 2, pageHeight - 26, { align: 'center' });
        }
    };

    // --- PAGE 1: EXECUTIVE SUMMARY ---
    addHeader();
    doc.setTextColor(44, 24, 90);
    doc.setFontSize(26);
    doc.setFont(undefined, 'bold');
    doc.text("Strategic Marketing Roadmap", 15, 45);
    
    doc.setFontSize(14);
    doc.setTextColor(100, 100, 100);
    doc.setFont(undefined, 'normal');
    doc.text(`Prepared for: ${clientName}`, 15, 55);

    const s = strategy?.output || {};
    
    // Positioning Box
    doc.setFillColor(245, 240, 255);
    doc.roundedRect(15, 65, pageWidth - 30, 40, 3, 3, 'F');
    doc.setTextColor(44, 24, 90);
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text("CORE BRAND POSITIONING & USP", 22, 75);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(10);
    const posText = doc.splitTextToSize(s.positioning || "Positioning framework analysis complete.", pageWidth - 45);
    doc.text(posText, 22, 83);

    // Channel Mix Analysis
    doc.setTextColor(44, 24, 90);
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text("Multi-Channel Distribution Strategy", 15, 120);

    const channels = typeof s.channel_mix === 'string' ? JSON.parse(s.channel_mix) : (s.channel_mix || []);
    doc.autoTable({
        startY: 125,
        head: [['Marketing Channel', 'Budget Allocation', 'Implementation Rationale']],
        body: channels.map((c: any) => [
            c.channel,
            `${c.weight}%`,
            c.reason
        ]),
        headStyles: { fillColor: [44, 24, 90], textColor: [255, 255, 255], fontStyle: 'bold' },
        bodyStyles: { fontSize: 10 },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        margin: { left: 15, right: 15 }
    });

    // Strategy Funnel Section
    const funnelY = (doc as any).lastAutoTable.finalY + 15;
    doc.setTextColor(44, 24, 90);
    doc.setFontSize(16);
    doc.text("Revenue & Lead Performance Forecast", 15, funnelY);

    const funnel = typeof s.funnel_model === 'string' ? JSON.parse(s.funnel_model) : (s.funnel_model || {});
    doc.autoTable({
        startY: funnelY + 5,
        body: [
            ['Projected Monthly Impressions', (funnel?.impressions || 0).toLocaleString()],
            ['Target Quality Leads', (funnel?.leads || 0).toLocaleString()],
            ['Estimated Sales Conversions', (funnel?.sales || 0).toLocaleString()],
            ['Projected Revenue Growth', `INR ${(funnel?.revenue || 0).toLocaleString()}`],
            ['Blended Conversion Target', `${funnel?.conversion_rate || '0'}%`]
        ],
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 6 },
        columnStyles: { 0: { fontStyle: 'bold', fillColor: [243, 244, 246], cellWidth: 80 } },
        margin: { left: 15, right: 15 }
    });

    addFooter();

    // --- PAGE 2: EXECUTION & AD STRATEGY ---
    doc.addPage();
    addHeader();
    
    // Execution Plan
    doc.setTextColor(44, 24, 90);
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text("Execution Roadmap (Phased Approach)", 15, 40);

    const plan = typeof s.execution_plan === 'string' ? JSON.parse(s.execution_plan) : (s.execution_plan || []);
    doc.autoTable({
        startY: 45,
        head: [['Operational Phase', 'Timeline', 'Key Strategic Milestones']],
        body: plan.map((p: any) => [
            p.phase,
            `Week ${p.week}`,
            Array.isArray(p.tasks) ? p.tasks.join(', ') : p.tasks
        ]),
        headStyles: { fillColor: [44, 24, 90], fontStyle: 'bold' },
        columnStyles: { 
            0: { fontStyle: 'bold', cellWidth: 40 },
            1: { cellWidth: 25 },
            2: { cellWidth: 100 }
        },
        styles: { fontSize: 9 }
    });

    // Content Strategy Insight
    const contentY = (doc as any).lastAutoTable.finalY + 15;
    doc.setTextColor(44, 24, 90);
    doc.setFontSize(14);
    doc.text("Tactical Content Direction", 15, contentY);
    
    doc.setFillColor(255, 252, 240); // Amber hint
    doc.roundedRect(15, contentY + 3, pageWidth - 30, 25, 2, 2, 'F');
    doc.setTextColor(150, 100, 0);
    doc.setFontSize(10);
    doc.setFont(undefined, 'bold');
    doc.text("EXPERT INSIGHT:", 20, contentY + 12);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(doc.splitTextToSize(s.ad_copy_framework || "Content should focus on value-driven storytelling and direct pain-point resolution.", pageWidth - 45), 20, contentY + 18);

    addFooter(true); // Last page with full contact details

    doc.save(`QixAds_Strategy_Report_${clientName.replace(/\s+/g, '_')}.pdf`);
};

/**
 * Robust Base64 to Uint8Array converter
 */
function base64ToUint8Array(base64: string): Uint8Array {
    try {
        const cleanBase64 = base64.replace(/\s/g, "");
        const binaryString = atob(cleanBase64);
        const bytes = new Uint8Array(binaryString.length);
        for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
        }
        return bytes;
    } catch (e) {
        console.error("Base64 Conversion Failed:", e);
        throw new Error("Invalid branding assets. Document generation aborted.");
    }
}

