import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import api from '../../../lib/api';
import { Card, CardHeader, CardTitle, CardContent } from '../../../components/ui/card';
import { Button } from '../../../components/ui/button';
import { IndianRupee, Users, TrendingUp, Award, Building2, Filter, Search } from 'lucide-react';
import { format } from 'date-fns';
import { useAuthStore } from '../../../store/authStore';

interface PerformanceKPIs {
    total_revenue: number;
    total_tasks: number;
    avg_revenue_per_task: number;
    top_contributor: any;
}

interface EmployeePerformance {
    employee: any;
    task_counts: Record<string, number>;
    total_revenue: number;
    total_tasks: number;
    tasks: any[];
    rank: number;
}

const TaskMonetaryCalculator = () => {
    const { user } = useAuthStore();
    const canView = ['DEVELOPER_ADMIN', 'ADMIN', 'MANAGER'].includes(user?.role || '');

    // Default to current month
    const [fromDate, setFromDate] = useState(() => {
        const d = new Date();
        d.setDate(1);
        return format(d, 'yyyy-MM-dd');
    });
    
    const [toDate, setToDate] = useState(() => {
        const d = new Date();
        d.setMonth(d.getMonth() + 1);
        d.setDate(0);
        return format(d, 'yyyy-MM-dd');
    });

    const [selectedEmployeeId, setSelectedEmployeeId] = useState('ALL');

    // Fetch staff for dropdown
    const { data: staff } = useQuery({
        queryKey: ['users'],
        queryFn: () => api.get('/users').then(res => res.data),
        enabled: canView
    });

    const creativeStaff = useMemo(() => {
        if (!staff) return [];
        return staff.filter((s: any) => s.department === 'CREATIVE');
    }, [staff]);

    const { data, isLoading } = useQuery<{ kpis: PerformanceKPIs, employee_performance: EmployeePerformance[], category_breakdown: Record<string, number>, raw_tasks: any[] }>({
        queryKey: ['monetary-performance', fromDate, toDate],
        queryFn: async () => {
            const body = { from_date: fromDate, to_date: toDate };
            return (await api.post('/creative-performance/calculate', body)).data;
        },
        enabled: canView
    });

    const filteredPerformance = useMemo(() => {
        if (!data?.employee_performance) return [];
        return data.employee_performance.filter(emp => {
            if (selectedEmployeeId === 'ALL') return true;
            return emp.employee?.id === selectedEmployeeId;
        });
    }, [data, selectedEmployeeId]);

    const dynamicKPIs = useMemo(() => {
        if (!filteredPerformance || filteredPerformance.length === 0) {
            return { total_revenue: 0, total_tasks: 0, avg_revenue_per_task: 0, top_contributor: 'N/A' };
        }
        let revenue = 0;
        let tasks = 0;
        let topRev = -1;
        let topName = 'N/A';
        
        filteredPerformance.forEach(emp => {
            revenue += emp.total_revenue || 0;
            tasks += emp.total_tasks || 0;
            if (emp.total_revenue > topRev) {
                topRev = emp.total_revenue;
                topName = emp.employee?.full_name || 'Unknown';
            }
        });
        
        return {
            total_revenue: revenue,
            total_tasks: tasks,
            avg_revenue_per_task: tasks > 0 ? revenue / tasks : 0,
            top_contributor: topName
        };
    }, [filteredPerformance]);

    if (!canView) {
        return (
            <Card>
                <CardContent className="p-12 text-center text-muted-foreground flex flex-col items-center">
                    <IndianRupee size={48} className="mb-4 opacity-50" />
                    <h2 className="text-xl font-bold mb-2">Access Denied</h2>
                    <p>You do not have permission to view the Task Monetary Calculator.</p>
                </CardContent>
            </Card>
        );
    }

    return (
        <div className="space-y-6">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h2 className="text-2xl font-bold tracking-tight text-gray-800">Task Monetary Calculator</h2>
                    <p className="text-muted-foreground">Measure approximate revenue contribution generated by each creative team member.</p>
                </div>
                
                <div className="flex items-center gap-2">
                    <Button variant="outline">Export PDF</Button>
                    <Button variant="outline">Export Excel</Button>
                </div>
            </div>

            {/* Filters */}
            <Card>
                <CardContent className="p-4 flex flex-col md:flex-row gap-4 items-center">
                    <div className="flex items-center gap-2 w-full md:w-auto">
                        <span className="text-sm font-medium text-gray-600">From</span>
                        <input 
                            type="date" 
                            className="bg-background border rounded-md px-3 py-2 text-sm focus:outline-none"
                            value={fromDate}
                            onChange={e => setFromDate(e.target.value)}
                        />
                    </div>
                    <div className="flex items-center gap-2 w-full md:w-auto">
                        <span className="text-sm font-medium text-gray-600">To</span>
                        <input 
                            type="date" 
                            className="bg-background border rounded-md px-3 py-2 text-sm focus:outline-none"
                            value={toDate}
                            onChange={e => setToDate(e.target.value)}
                        />
                    </div>
                    <div className="flex-1 w-full relative">
                        <select 
                            className="w-full px-4 py-2 bg-background border rounded-md focus:outline-none text-sm appearance-none"
                            value={selectedEmployeeId}
                            onChange={e => setSelectedEmployeeId(e.target.value)}
                        >
                            <option value="ALL">All Creative Staff</option>
                            {creativeStaff.map((emp: any) => (
                                <option key={emp.id} value={emp.id}>
                                    {emp.full_name}
                                </option>
                            ))}
                        </select>
                        <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-500">
                            <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                        </div>
                    </div>
                </CardContent>
            </Card>

            {/* KPIs */}
            {isLoading ? (
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4 animate-pulse">
                    {[1, 2, 3, 4].map(i => <div key={i} className="h-32 bg-gray-100 rounded-xl" />)}
                </div>
            ) : data && (
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <Card className="bg-gradient-to-br from-indigo-500 to-purple-600 text-white">
                        <CardContent className="p-6">
                            <div className="flex justify-between items-start">
                                <div>
                                    <p className="text-indigo-100 text-sm font-medium mb-1">Total Contribution</p>
                                    <h3 className="text-3xl font-bold">₹{dynamicKPIs.total_revenue.toLocaleString()}</h3>
                                </div>
                                <div className="p-3 bg-white/20 rounded-lg"><IndianRupee className="w-6 h-6" /></div>
                            </div>
                        </CardContent>
                    </Card>
                    
                    <Card>
                        <CardContent className="p-6">
                            <div className="flex justify-between items-start">
                                <div>
                                    <p className="text-muted-foreground text-sm font-medium mb-1">Total Completed Tasks</p>
                                    <h3 className="text-3xl font-bold text-gray-800">{dynamicKPIs.total_tasks}</h3>
                                </div>
                                <div className="p-3 bg-blue-50 text-blue-600 rounded-lg"><TrendingUp className="w-6 h-6" /></div>
                            </div>
                        </CardContent>
                    </Card>
                    
                    <Card>
                        <CardContent className="p-6">
                            <div className="flex justify-between items-start">
                                <div>
                                    <p className="text-muted-foreground text-sm font-medium mb-1">Avg. Revenue / Task</p>
                                    <h3 className="text-3xl font-bold text-gray-800">₹{dynamicKPIs.avg_revenue_per_task.toLocaleString(undefined, { maximumFractionDigits: 0 })}</h3>
                                </div>
                                <div className="p-3 bg-green-50 text-green-600 rounded-lg"><IndianRupee className="w-6 h-6" /></div>
                            </div>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardContent className="p-6">
                            <div className="flex justify-between items-start">
                                <div>
                                    <p className="text-muted-foreground text-sm font-medium mb-1">Top Contributor</p>
                                    <h3 className="text-xl font-bold text-gray-800 break-words">{dynamicKPIs.top_contributor}</h3>
                                </div>
                                <div className="p-3 bg-orange-50 text-orange-600 rounded-lg"><Award className="w-6 h-6" /></div>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            )}

            {/* Category Breakdown */}
            {data && data.category_breakdown && Object.keys(data.category_breakdown).length > 0 && (
                <Card>
                    <CardHeader className="bg-gray-50/50 border-b pb-4">
                        <CardTitle className="text-lg">Category-wise Revenue Breakdown</CardTitle>
                    </CardHeader>
                    <CardContent className="p-6">
                        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
                            {Object.entries(data.category_breakdown).map(([category, amount]) => (
                                <div key={category} className="bg-white border rounded-lg p-4 shadow-sm hover:shadow-md transition-shadow">
                                    <p className="text-sm text-gray-500 font-medium mb-1 truncate" title={category}>{category}</p>
                                    <h4 className="text-xl font-bold text-gray-800">₹{amount.toLocaleString()}</h4>
                                </div>
                            ))}
                        </div>
                    </CardContent>
                </Card>
            )}

            {/* Performance Table */}
            <Card>
                <CardHeader className="bg-gray-50/50 border-b pb-4">
                    <CardTitle className="text-lg">Team Performance & Contribution</CardTitle>
                </CardHeader>
                <CardContent className="p-0">
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm text-left">
                            <thead className="bg-gray-50 text-gray-600 font-medium border-b">
                                <tr>
                                    <th className="px-6 py-4">Rank</th>
                                    <th className="px-6 py-4">Employee Name</th>
                                    <th className="px-6 py-4">Total Tasks</th>
                                    <th className="px-6 py-4">Revenue Contribution</th>
                                    <th className="px-6 py-4">Avg Per Task</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y">
                                {isLoading ? (
                                    <tr><td colSpan={5} className="p-8 text-center text-muted-foreground">Calculating revenue contributions...</td></tr>
                                ) : filteredPerformance.length === 0 ? (
                                    <tr><td colSpan={5} className="p-8 text-center text-muted-foreground">No tasks found for the selected period.</td></tr>
                                ) : (
                                    filteredPerformance.map((emp) => (
                                        <tr key={emp.employee?.id} className="hover:bg-gray-50/50 transition-colors">
                                            <td className="px-6 py-4 font-bold text-gray-500">#{emp.rank}</td>
                                            <td className="px-6 py-4 font-medium text-indigo-700">{emp.employee?.full_name || 'Unknown'}</td>
                                            <td className="px-6 py-4 font-semibold">{emp.total_tasks}</td>
                                            <td className="px-6 py-4 font-bold text-green-700">₹{emp.total_revenue.toLocaleString()}</td>
                                            <td className="px-6 py-4 text-gray-500">₹{(emp.total_revenue / emp.total_tasks).toLocaleString(undefined, { maximumFractionDigits: 0 })}</td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </CardContent>
            </Card>

        </div>
    );
};

export default TaskMonetaryCalculator;
