export const ROLES = {
    DEVELOPER_ADMIN: 'DEVELOPER_ADMIN', // Implicit super-admin
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    DM_EXECUTIVE: 'DM_EXECUTIVE',
    WEB_SEO_EXECUTIVE: 'WEB_SEO_EXECUTIVE',
    CREATIVE_DESIGNER: 'CREATIVE_DESIGNER',
    OPERATIONS_EXECUTIVE: 'OPERATIONS_EXECUTIVE',
    CLIENT: 'CLIENT',
} as const;

export type Role = keyof typeof ROLES;

export const ROLE_GROUPS = {
    ALL_ADMINS: [ROLES.DEVELOPER_ADMIN, ROLES.ADMIN],
    MANAGEMENT: [ROLES.DEVELOPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
    STAFF: [
        ROLES.MANAGER,
        ROLES.DM_EXECUTIVE,
        ROLES.WEB_SEO_EXECUTIVE,
        ROLES.CREATIVE_DESIGNER,
        ROLES.OPERATIONS_EXECUTIVE
    ],
    ALL_INTERNAL: [
        ROLES.DEVELOPER_ADMIN,
        ROLES.ADMIN,
        ROLES.MANAGER,
        ROLES.DM_EXECUTIVE,
        ROLES.WEB_SEO_EXECUTIVE,
        ROLES.CREATIVE_DESIGNER,
        ROLES.OPERATIONS_EXECUTIVE
    ]
};

export const ROLE_LABELS: Record<string, string> = {
    [ROLES.DEVELOPER_ADMIN]: 'Developer Admin',
    [ROLES.ADMIN]: 'Admin',
    [ROLES.MANAGER]: 'Manager',
    [ROLES.DM_EXECUTIVE]: 'DM Executive',
    [ROLES.WEB_SEO_EXECUTIVE]: 'SEO Executive',
    [ROLES.CREATIVE_DESIGNER]: 'Designer',
    [ROLES.OPERATIONS_EXECUTIVE]: 'Operations',
    [ROLES.CLIENT]: 'Client',
};
